/**
 * Bootstrap script generator.
 *
 * Generates the shell script that sets up proot-distro Ubuntu with all
 * required tooling for running Codex CLI inside Termux.
 *
 * The script writes progress markers (STEP:N / DONE:N) to a log file
 * so the React Native app can track progress by polling.
 */

/** Log file path inside Termux home where the bootstrap script writes progress */
export const BOOTSTRAP_LOG = '/data/data/com.termux/files/home/codex-bootstrap.log';

/** Total number of setup steps */
export const TOTAL_STEPS = 6;

/** Human-readable labels for each step */
export const STEP_LABELS: Record<number, string> = {
  1: 'Installing proot-distro',
  2: 'Installing Ubuntu',
  3: 'Installing system packages (nodejs, git, gcc, python3, gh)',
  4: 'Installing Codex CLI',
  5: 'Compiling prctl shim',
  6: 'Creating launcher script',
};

/**
 * C source for the prctl LD_PRELOAD shim.
 *
 * Codex CLI crashes inside proot because prctl(PR_SET_DUMPABLE) fails.
 * This shim intercepts that specific call and returns 0 (success).
 */
export const PRCTL_SHIM_SOURCE = `
#define _GNU_SOURCE
#include <sys/prctl.h>
#include <dlfcn.h>
#include <stdarg.h>

typedef int (*orig_prctl_fn)(int, ...);

int prctl(int option, ...) {
    if (option == PR_SET_DUMPABLE) {
        return 0;
    }

    orig_prctl_fn orig = (orig_prctl_fn)dlsym(RTLD_NEXT, "prctl");

    va_list args;
    va_start(args, option);
    unsigned long a2 = va_arg(args, unsigned long);
    unsigned long a3 = va_arg(args, unsigned long);
    unsigned long a4 = va_arg(args, unsigned long);
    unsigned long a5 = va_arg(args, unsigned long);
    va_end(args);

    return orig(option, a2, a3, a4, a5);
}
`.trim();

/**
 * Generate the launcher script that starts the Codex app-server.
 *
 * @param apiKey    - OpenAI API key
 */
export function generateLauncherScript(
  apiKey: string,
): string {
  return `#!/bin/bash
# Codex app-server launcher — generated by Codex for Android
export OPENAI_API_KEY="${apiKey}"
export LD_PRELOAD=/usr/lib/libprctl_shim.so

exec codex app-server --listen ws://127.0.0.1:4500
`.trim();
}

/**
 * Generate the full bootstrap script.
 *
 * This script is written to Termux home and executed via RUN_COMMAND intent.
 * It installs proot-distro Ubuntu and all dependencies, then creates the
 * launcher script.
 *
 * @param apiKey - The OpenAI API key to embed in the launcher
 */
export function generateBootstrapScript(apiKey: string): string {
  const launcherContent = generateLauncherScript(apiKey);

  return `#!/bin/bash
set -e

LOG="${BOOTSTRAP_LOG}"
echo "" > "$LOG"

log_step() { echo "STEP:$1" >> "$LOG"; }
log_done() { echo "DONE:$1" >> "$LOG"; }
log_error() { echo "ERROR:$1:$2" >> "$LOG"; }

# Step 1: Install proot-distro
log_step 1
pkg install -y proot-distro 2>>"$LOG" || { log_error 1 "Failed to install proot-distro"; exit 1; }
log_done 1

# Step 2: Install Ubuntu
log_step 2
proot-distro install ubuntu 2>>"$LOG" || true  # OK if already installed
log_done 2

# Step 3: Install system packages inside Ubuntu
log_step 3
proot-distro login ubuntu -- bash -c '
  apt-get update -y && \\
  apt-get install -y nodejs npm git gh gcc python3 curl
' 2>>"$LOG" || { log_error 3 "Failed to install packages"; exit 1; }
log_done 3

# Step 4: Install Codex CLI
log_step 4
proot-distro login ubuntu -- bash -c '
  npm install -g @openai/codex
' 2>>"$LOG" || { log_error 4 "Failed to install Codex CLI"; exit 1; }
log_done 4

# Step 5: Compile prctl shim
log_step 5
proot-distro login ubuntu -- bash -c '
  cat > /tmp/prctl_shim.c << "SHIMEOF"
${PRCTL_SHIM_SOURCE}
SHIMEOF
  gcc -shared -fPIC -o /usr/lib/libprctl_shim.so /tmp/prctl_shim.c -ldl && \\
  echo "LD_PRELOAD=/usr/lib/libprctl_shim.so" >> /etc/environment && \\
  rm /tmp/prctl_shim.c
' 2>>"$LOG" || { log_error 5 "Failed to compile prctl shim"; exit 1; }
log_done 5

# Step 6: Create launcher script
log_step 6
proot-distro login ubuntu -- bash -c 'cat > /root/start-codex.sh << "LAUNCHEREOF"
${launcherContent}
LAUNCHEREOF
chmod +x /root/start-codex.sh
' 2>>"$LOG" || { log_error 6 "Failed to create launcher"; exit 1; }
log_done 6

echo "BOOTSTRAP_COMPLETE" >> "$LOG"
`;
}

/**
 * Parse the bootstrap log to determine current progress.
 *
 * @param logContent - Raw content of the bootstrap log file
 * @returns Current step number, completed steps, and any errors
 */
export function parseBootstrapLog(logContent: string): {
  currentStep: number;
  completedSteps: number[];
  error: { step: number; message: string } | null;
  isComplete: boolean;
} {
  const lines = logContent.split('\n');
  const completedSteps: number[] = [];
  let currentStep = 0;
  let error: { step: number; message: string } | null = null;
  let isComplete = false;

  for (const line of lines) {
    const stepMatch = line.match(/^STEP:(\d+)$/);
    if (stepMatch) {
      currentStep = parseInt(stepMatch[1], 10);
    }
    const doneMatch = line.match(/^DONE:(\d+)$/);
    if (doneMatch) {
      completedSteps.push(parseInt(doneMatch[1], 10));
    }
    const errorMatch = line.match(/^ERROR:(\d+):(.+)$/);
    if (errorMatch) {
      error = { step: parseInt(errorMatch[1], 10), message: errorMatch[2] };
    }
    if (line.trim() === 'BOOTSTRAP_COMPLETE') {
      isComplete = true;
    }
  }

  return { currentStep, completedSteps, error, isComplete };
}
